const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    //=====================================================================
    // The module. Pure Zig, no dependencies, nothing to link: zlib comes
    // from `std.compress.flate` and the two hashes from `std.crypto`, so a
    // consumer's build graph has nothing to configure and nothing to
    // disagree with.
    //=====================================================================

    const module = b.addModule("relic", .{
        .root_source_file = b.path("src/relic.zig"),
        .target = target,
        .optimize = optimize,
    });

    //=====================================================================
    // Tests. The suite lives beside the code it tests, so the root module's
    // imports are what pull every file in. Fixtures are generated by the
    // `git` on the machine at test time, into a temporary directory; a
    // machine with no `git` skips those tests rather than failing them.
    //=====================================================================

    // A second process is the only honest way to prove that a lock a
    // running git holds is refused rather than broken, so the suite spawns
    // one. Its path is compiled into the test binary rather than passed in
    // the environment, because nothing in this package reads one.
    const lock_helper = b.addExecutable(.{
        .name = "relic-lock-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/lock_helper.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_lock_helper = b.addInstallArtifact(lock_helper, .{});

    const build_options = b.addOptions();
    build_options.addOption([]const u8, "lock_helper_path", b.getInstallPath(.bin, lock_helper.out_filename));

    // Error return traces are off for the test binary, and the reason is
    // `zig build test --fuzz`. Building the suite with fuzzing instrumented
    // recompiles it against the fuzzing test runner, and on 0.16.0 that
    // runner hands `@errorReturnTrace()`'s `std.builtin.StackTrace` to a
    // function taking `std.debug.StackTrace` -- two structs of the same
    // shape and different identity -- which is one compile error per fuzz
    // test. With tracing off nothing in the runner asks for a trace, and the
    // fuzzers build and run. What it costs is the return trace under a
    // failing test; the error and the test's name are still printed.
    const test_module = b.createModule(.{
        .root_source_file = b.path("src/relic.zig"),
        .target = target,
        .optimize = optimize,
        .error_tracing = false,
    });
    test_module.addOptions("build_options", build_options);

    const tests = b.addTest(.{
        .name = "relic-tests",
        .root_module = test_module,
    });

    const run_tests = b.addRunArtifact(tests);
    run_tests.step.dependOn(&install_lock_helper.step);

    const test_step = b.step("test", "Run the relic tests");
    test_step.dependOn(&run_tests.step);

    // Compiling without running: the step a cross-compilation check uses,
    // and the one an editor can keep warm. It covers the tests too, which
    // the default install step does not.
    const check_step = b.step("check", "Compile everything without running it");
    check_step.dependOn(&tests.step);
    check_step.dependOn(&lock_helper.step);

    //=====================================================================
    // Examples
    //
    // Built AND run, against the module a consumer gets. An example that is
    // only compiled proves the names still resolve; running it is what
    // proves the bytes are still the bytes. examples/usage.zig is also where
    // README.md's Usage block comes from -- see ci/readme_usage.sh -- so the
    // snippet a reader copies cannot drift from code CI executes.
    //=====================================================================

    const examples_step = b.step("examples", "Build and run the examples");
    for (example_sources) |source| {
        const example = b.addExecutable(.{
            .name = std.fs.path.stem(source),
            .root_module = b.createModule(.{
                .root_source_file = b.path(source),
                .target = target,
                .optimize = optimize,
                .imports = &.{.{ .name = "relic", .module = module }},
            }),
        });
        b.installArtifact(example);
        check_step.dependOn(&example.step);
        const run = b.addRunArtifact(example);
        run.step.dependOn(b.getInstallStep());
        run.setCwd(b.path("zig-out"));
        examples_step.dependOn(&run.step);
    }
    test_step.dependOn(examples_step);
}

/// Every example, listed rather than globbed: a build graph that scans a
/// directory is not reproducible from the manifest alone.
const example_sources = [_][]const u8{
    "examples/usage.zig",
};
