const std = @import("std");

pub fn build(b: *std.Build) void {
    const std_tls_client = b.graph.path(.zig_lib, "std/crypto/tls/Client.zig");
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    //=====================================================================
    // The module. Conduit runs programs and carries its platform linkage;
    // command preparation and the permission to run remain here.
    //=====================================================================

    const conduit = b.dependency("conduit", .{ .target = target, .optimize = optimize }).module("conduit");

    const module = b.addModule("relic", .{
        .root_source_file = b.path("src/relic.zig"),
        .target = target,
        .optimize = optimize,
    });

    module.addImport("conduit", conduit);

    //=====================================================================
    // Tests. The suite lives beside the code it tests, so the root module's
    // imports are what pull every file in. Fixtures are generated by the
    // `git` on the machine at test time, into a temporary directory; a
    // machine with no `git` skips those tests rather than failing them.
    //=====================================================================

    // A second process is the only honest way to prove that a lock a
    // running git holds is refused rather than broken, so the suite spawns
    // one. Its path is compiled into the test binary rather than passed in
    // the environment, because nothing in this package reads one.
    const lock_helper = b.addExecutable(.{
        .name = "relic-lock-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lock.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // A long-running filter process has to be a program for the same
    // reason: relic and git are each handed it as `filter.<driver>.process`
    // and what they store is compared.
    const filter_helper = b.addExecutable(.{
        .name = "relic-filter-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/filter.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // git-lfs does not ship a `git-lfs-transfer` server, so the suite
    // brings one: relic and git-lfs are each pointed at it over the same
    // stand-in ssh and what it was asked is compared.
    const lfs_transfer_helper = b.addExecutable(.{
        .name = "relic-lfs-transfer-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lfs/transfer.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // relic's own upload-pack, as a program real git can be pointed at with
    // `--upload-pack`, so what git makes of relic's server is compared with
    // what it makes of its own.
    const upload_pack_helper = b.addExecutable(.{
        .name = "relic-upload-pack",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/uploadpack.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // Hook fixtures use a native program on every target. Each copy reads
    // its own sidecar description, so git and relic run the same behaviour.
    const hook_fixture = b.addExecutable(.{
        .name = "relic-hook-fixture",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/hook.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    const fake_ssh = b.addExecutable(.{
        .name = "relic-fake-ssh",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/fake_ssh.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    const lfs_tool = b.addExecutable(.{
        .name = "relic-lfs-test-tool",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lfs/tool.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // A remote helper, for git and relic to be pointed at alike: git's
    // own `git-remote-testgit`, and one with `fetch` and `push`.
    const remote_helper = b.addExecutable(.{
        .name = "relic-remote-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/remotehelper.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    // A custom LFS transfer agent, handed to git-lfs and to relic alike.
    const lfs_agent = b.addExecutable(.{
        .name = "relic-lfs-agent",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lfs/agent.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    const process_fixture = b.addExecutable(.{
        .name = "relic-process-fixture",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/process.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    const build_options = b.addOptions();
    const gnupg_fixture_root = b.option(
        []const u8,
        "gnupg-fixture-root",
        "A short directory for private GnuPG test homes (defaults to .zig-cache/gpg)",
    ) orelse ".zig-cache/gpg";
    build_options.addOptionPathUntracked("gnupg_fixture_root", if (std.Io.Dir.path.isAbsolute(gnupg_fixture_root))
        b.graph.cwdRelativePath(gnupg_fixture_root)
    else
        b.path(gnupg_fixture_root));
    build_options.addOptionPath("lock_helper_path", lock_helper.getEmittedBin());
    build_options.addOptionPath("filter_helper_path", filter_helper.getEmittedBin());
    build_options.addOptionPath("lfs_transfer_helper_path", lfs_transfer_helper.getEmittedBin());
    // A real `git-lfs-transfer` server — Scutiger's is the one git-lfs's
    // own suite uses — for the tests that prove relic's client against one
    // rather than against the suite's own; they skip without it.
    build_options.addOption([]const u8, "lfs_transfer_server", b.option(
        []const u8,
        "lfs-transfer-server",
        "A git-lfs-transfer server program to prove the pure-ssh client against",
    ) orelse "");
    build_options.addOptionPath("upload_pack_helper_path", upload_pack_helper.getEmittedBin());
    build_options.addOptionPath("hook_fixture_path", hook_fixture.getEmittedBin());
    build_options.addOptionPath("fake_ssh_helper_path", fake_ssh.getEmittedBin());
    build_options.addOptionPath("lfs_test_tool_path", lfs_tool.getEmittedBin());
    build_options.addOptionPath("process_fixture_path", process_fixture.getEmittedBin());
    build_options.addOptionPath("remote_helper_path", remote_helper.getEmittedBin());
    build_options.addOptionPath("lfs_agent_path", lfs_agent.getEmittedBin());
    // The standard library's TLS client, which `src/transport/tls/Client.zig` is a copy
    // of with client authentication added: `src/testing/tls_fork.zig` holds the
    // copy to it, and fails when the compiler building this ships another.
    // Hosted Zig installations use a fresh temporary path on every job, so the
    // suite embeds a copy of the file rather than its path: a copy's path
    // follows its bytes, and the test binaries stay cached across CI runs.
    const std_client = b.addWriteFiles();
    _ = std_client.addCopyFile(std_tls_client, "Client.zig.txt");
    const std_client_module = b.createModule(.{
        .root_source_file = std_client.add("std_tls_client.zig", "pub const source = @embedFile(\"Client.zig.txt\");\n"),
    });

    // The delta search runs its candidates on the caller's executor when
    // `PackOptions.threads` asks for more than one, and the suite writes
    // the same repository from two processes and two tasks at once. Whether
    // that is free of races is a claim a race detector can check and a
    // reader cannot: `zig build test -Dthread-sanitizer`.
    const thread_sanitizer = b.option(
        bool,
        "thread-sanitizer",
        "Build the tests with ThreadSanitizer",
    ) orelse false;

    const test_module = b.createModule(.{
        .root_source_file = b.path("src/tests.zig"),
        .target = target,
        .optimize = optimize,
        .sanitize_thread = if (thread_sanitizer) true else null,
    });
    test_module.addImport("conduit", conduit);
    test_module.addImport("std_tls_client", std_client_module);
    filter_helper.root_module.addImport("relic", module);
    lfs_transfer_helper.root_module.addImport("relic", module);
    hook_fixture.root_module.addImport("relic", module);
    upload_pack_helper.root_module.addImport("relic", module);
    upload_pack_helper.root_module.addImport("conduit", conduit);
    hook_fixture.root_module.addImport("conduit", conduit);
    test_module.addOptions("build_options", build_options);

    const tests = b.addTest(.{
        .name = "relic-tests",
        .root_module = test_module,
        .filters = if (b.option([]const u8, "test-filter", "Select tests by name")) |filter| &.{filter} else &.{},
    });

    const run_tests = b.addRunArtifact(tests);

    const test_step = b.step("test", "Run the relic tests");
    test_step.dependOn(&run_tests.step);

    // Compiling without running: the step a cross-compilation check uses,
    // and the one an editor can keep warm. It covers the tests too, which
    // the default install step does not.
    const check_step = b.step("check", "Compile everything without running it");
    check_step.dependOn(&tests.step);
    check_step.dependOn(&lock_helper.step);
    check_step.dependOn(&filter_helper.step);
    check_step.dependOn(&lfs_transfer_helper.step);
    check_step.dependOn(&upload_pack_helper.step);
    check_step.dependOn(&hook_fixture.step);
    check_step.dependOn(&fake_ssh.step);
    check_step.dependOn(&lfs_tool.step);
    check_step.dependOn(&process_fixture.step);
    check_step.dependOn(&remote_helper.step);
    check_step.dependOn(&lfs_agent.step);

    //=====================================================================
    // Examples
    //
    // Built AND run, against the module a consumer gets. An example that is
    // only compiled proves the names still resolve; running it is what
    // proves the bytes are still the bytes. examples/usage.zig is also where
    // README.md's Usage block comes from -- see zig build docs -- usage -- so the
    // snippet a reader copies cannot drift from code CI executes.
    //=====================================================================

    const examples_step = b.step("examples", "Build and run the examples");
    for (example_sources) |source| {
        const example = b.addExecutable(.{
            .name = std.Io.Dir.path.stem(source),
            .root_module = b.createModule(.{
                .root_source_file = b.path(source),
                .target = target,
                .optimize = optimize,
                .imports = &.{.{ .name = "relic", .module = module }},
            }),
        });
        b.installArtifact(example);
        check_step.dependOn(&example.step);
        const run = b.addRunArtifact(example);
        run.step.dependOn(b.getInstallStep());
        run.setCwd(b.path("zig-out"));
        examples_step.dependOn(&run.step);

        const example_tests = b.addTest(.{ .root_module = example.root_module });
        const run_example_tests = b.addRunArtifact(example_tests);
        if (target.result.os.tag == .windows) {
            // Zig inherits all inheritable Windows pipe handles at
            // spawn. Concurrent runners can keep each other's pipes open.
            run_example_tests.step.dependOn(&run_tests.step);
            run.step.dependOn(&run_example_tests.step);
        }
        examples_step.dependOn(&run_example_tests.step);
        check_step.dependOn(&example_tests.step);
    }
    test_step.dependOn(examples_step);

    //=====================================================================
    // Benchmarks
    //
    // relic's own measurements of its own work, in bench/: `zig build bench
    // -Doptimize=ReleaseFast` installs them under zig-out/bench, and `zig
    // build check` compiles them, so they keep up with the API. They run on a
    // quiet machine, never in CI; bench/README.md says how. Only in relic's
    // own tree: a package fetched by a consumer has no bench/.
    //=====================================================================

    if (b.pkg_hash.len == 0) {
        const bench_step = b.step("bench", "Build the benchmarks into zig-out/bench");
        const bench_options = b.addOptions();
        bench_options.addOption(bool, "smoke", b.option(bool, "bench-smoke", "Benchmarks run every point once and read no clock") orelse false);
        const regressions = b.addTest(.{
            .name = "relic-regressions",
            .root_module = b.createModule(.{
                .root_source_file = b.path("bench/regressions.zig"),
                .target = target,
                .optimize = optimize,
                .imports = &.{
                    .{ .name = "relic", .module = module },
                    .{ .name = "bench_options", .module = bench_options.createModule() },
                },
            }),
            .filters = &.{"benchmark:"},
        });
        bench_step.dependOn(&b.addInstallArtifact(regressions, .{ .dest_dir = .{ .override = .{ .custom = "bench" } } }).step);
        check_step.dependOn(&regressions.step);
    }
    // The CI gate is the repository's own, never a consumer's: a project
    // that depends on relic neither fetches preflight nor imports it.
    if (b.pkg_hash.len == 0) {
        if (b.lazyImport(@This(), "preflight")) |preflight| preflight.addCi(b, .{ .tests = test_step });
    }
    namespaceImportChecker(b);
    const setup = b.addExecutable(.{ .name = "ci-setup", .root_module = b.createModule(.{ .root_source_file = b.path("ci/setup.zig"), .target = b.graph.host, .optimize = .safe }) });
    const prepare = b.addRunArtifact(setup);
    prepare.addPassthruArgs();
    b.step("ci-setup", "Install cached Git and LFS tools").dependOn(&prepare.step);
    // The installer runs only on a hosted runner; its version reading is
    // proved everywhere.
    b.step("check-ci-setup", "Test the hosted tool installer").dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = setup.root_module })).step);
    // Keep the package root at src so the moved check can embed its TLS sibling.
    const tls_test = b.addTest(.{ .root_module = test_module, .filters = &.{"the TLS client is std's, with the recorded diff and nothing else"} });
    b.step("check-tls-fork", "Verify the TLS fork against std and its recorded patch").dependOn(&b.addRunArtifact(tls_test).step);
    const tls_writer = b.addExecutable(.{ .name = "tls-fork", .root_module = b.createModule(.{ .root_source_file = b.path("ci/tls_fork.zig"), .target = b.graph.host, .optimize = .safe }) });
    const tls_writer_options = b.addOptions();
    tls_writer_options.addOptionPath("std_tls_client", std_tls_client);
    tls_writer.root_module.addOptions("build_options", tls_writer_options);
    b.step("tls-fork", "Re-record the TLS client's patch against std").dependOn(&b.addRunArtifact(tls_writer).step);
}

/// Every example, listed rather than globbed: a build graph that scans a
/// directory is not reproducible from the manifest alone.
const example_sources = [_][]const u8{
    "examples/usage.zig",
};

// Main keeps namespace reexports outside implementation layer and cycle
// checks, which preflight's structure check has no declaration for yet. Both
// of preflight's structure runs (check-imports and lint) share one compile
// step, so relic's checker replaces that step's source.
fn namespaceImportChecker(b: *std.Build) void {
    if (b.pkg_hash.len != 0) return;
    const structure = b.top_level_steps.get("check-imports") orelse return;
    for (structure.step.dependencies.items) |dependency| {
        const run = dependency.cast(std.Build.Step.Run) orelse continue;
        const checker = run.producer orelse continue;
        if (!std.mem.eql(u8, checker.name, "preflight-structure")) continue;
        checker.root_module.root_source_file = b.path("ci/imports.zig");
        return;
    }
    @panic("check-imports: preflight's structure checker not found");
}
