const std = @import("std");
const preflight = @import("preflight");
const test_cases = @import("ci/test_cases.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const selected_case = b.option([]const u8, "test-case", "Select a named Windows comparison shard");
    const case_names = if (selected_case) |name| test_cases.filters(b, name) else &.{};
    const case_options = b.addOptions();
    case_options.addOption([]const u8, "name", selected_case orelse "");
    case_options.addOption([]const []const u8, "names", case_names);

    //=====================================================================
    // The module. Conduit runs programs and carries its platform linkage;
    // command preparation and the permission to run remain here.
    //=====================================================================

    const conduit = b.dependency("conduit", .{ .target = target, .optimize = optimize }).module("conduit");

    const module = b.addModule("relic", .{
        .root_source_file = b.path("src/relic.zig"),
        .target = target,
        .optimize = optimize,
    });

    module.addImport("conduit", conduit);
    module.addOptions("relic_test_cases", case_options);

    //=====================================================================
    // Tests. The suite lives beside the code it tests, so the root module's
    // imports are what pull every file in. Fixtures are generated by the
    // `git` on the machine at test time, into a temporary directory; a
    // machine with no `git` skips those tests rather than failing them.
    //=====================================================================

    // A second process is the only honest way to prove that a lock a
    // running git holds is refused rather than broken, so the suite spawns
    // one. Its path is compiled into the test binary rather than passed in
    // the environment, because nothing in this package reads one.
    const lock_helper = b.addExecutable(.{
        .name = "relic-lock-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lock.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_lock_helper = b.addInstallArtifact(lock_helper, .{});

    // A long-running filter process has to be a program for the same
    // reason: relic and git are each handed it as `filter.<driver>.process`
    // and what they store is compared.
    const filter_helper = b.addExecutable(.{
        .name = "relic-filter-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/filter.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_filter_helper = b.addInstallArtifact(filter_helper, .{});

    // git-lfs does not ship a `git-lfs-transfer` server, so the suite
    // brings one: relic and git-lfs are each pointed at it over the same
    // stand-in ssh and what it was asked is compared.
    const lfs_transfer_helper = b.addExecutable(.{
        .name = "relic-lfs-transfer-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lfs/transfer.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_lfs_transfer_helper = b.addInstallArtifact(lfs_transfer_helper, .{});

    // relic's own upload-pack, as a program real git can be pointed at with
    // `--upload-pack`, so what git makes of relic's server is compared with
    // what it makes of its own.
    const upload_pack_helper = b.addExecutable(.{
        .name = "relic-upload-pack",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/uploadpack.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_upload_pack_helper = b.addInstallArtifact(upload_pack_helper, .{});

    // Hook fixtures use a native program on every target. Each copy reads
    // its own sidecar description, so git and relic run the same behaviour.
    const hook_fixture = b.addExecutable(.{
        .name = "relic-hook-fixture",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/hook.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_hook_fixture = b.addInstallArtifact(hook_fixture, .{});

    const fake_ssh = b.addExecutable(.{
        .name = "relic-fake-ssh",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/fake_ssh.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_fake_ssh = b.addInstallArtifact(fake_ssh, .{});

    const lfs_tool = b.addExecutable(.{
        .name = "relic-lfs-test-tool",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/lfs/tool.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_lfs_tool = b.addInstallArtifact(lfs_tool, .{});

    // A remote helper, for git and relic to be pointed at alike: git's
    // own `git-remote-testgit`, and one with `fetch` and `push`.
    const remote_helper = b.addExecutable(.{
        .name = "relic-remote-helper",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/remotehelper.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_remote_helper = b.addInstallArtifact(remote_helper, .{});

    const process_fixture = b.addExecutable(.{
        .name = "relic-process-fixture",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/testing/process.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const install_process_fixture = b.addInstallArtifact(process_fixture, .{});

    const build_options = b.addOptions();
    build_options.addOption([]const u8, "gnupg_fixture_root", b.pathFromRoot(b.option(
        []const u8,
        "gnupg-fixture-root",
        "A short directory for private GnuPG test homes (defaults to .zig-cache/gpg)",
    ) orelse ".zig-cache/gpg"));
    build_options.addOption([]const u8, "lock_helper_path", b.getInstallPath(.bin, lock_helper.out_filename));
    build_options.addOption([]const u8, "filter_helper_path", b.getInstallPath(.bin, filter_helper.out_filename));
    build_options.addOption([]const u8, "lfs_transfer_helper_path", b.getInstallPath(.bin, lfs_transfer_helper.out_filename));
    // A real `git-lfs-transfer` server — Scutiger's is the one git-lfs's
    // own suite uses — for the tests that prove relic's client against one
    // rather than against the suite's own; they skip without it.
    build_options.addOption([]const u8, "lfs_transfer_server", b.option(
        []const u8,
        "lfs-transfer-server",
        "A git-lfs-transfer server program to prove the pure-ssh client against",
    ) orelse "");
    build_options.addOption([]const u8, "upload_pack_helper_path", b.getInstallPath(.bin, upload_pack_helper.out_filename));
    build_options.addOption([]const u8, "hook_fixture_path", b.getInstallPath(.bin, hook_fixture.out_filename));
    build_options.addOption([]const u8, "fake_ssh_helper_path", b.getInstallPath(.bin, fake_ssh.out_filename));
    build_options.addOption([]const u8, "lfs_test_tool_path", b.getInstallPath(.bin, lfs_tool.out_filename));
    build_options.addOption([]const u8, "process_fixture_path", b.getInstallPath(.bin, process_fixture.out_filename));
    build_options.addOption([]const u8, "remote_helper_path", b.getInstallPath(.bin, remote_helper.out_filename));
    // The standard library's TLS client, which `src/transport/tls/Client.zig` is a copy
    // of with client authentication added: `src/testing/tls_fork.zig` holds the
    // copy to it, and fails when the compiler building this ships another.
    // Hosted Zig installations use a fresh temporary path on every job. The
    // compiler's bytes belong in the test options so that path cannot invalidate
    // every native and cross-target test binary on each CI run.
    const std_client = b.graph.zig_lib_directory.handle.readFileAlloc(b.graph.io, "std/crypto/tls/Client.zig", b.allocator, .limited(1 << 20)) catch @panic("cannot read std's TLS client");
    build_options.addOption([]const u8, "std_tls_client_source", std_client);

    // Error return traces are off for the test binary, and the reason is
    // `zig build test --fuzz`. Building the suite with fuzzing instrumented
    // recompiles it against the fuzzing test runner, and on 0.16.0 that
    // runner hands `@errorReturnTrace()`'s `std.builtin.StackTrace` to a
    // function taking `std.debug.StackTrace` -- two structs of the same
    // shape and different identity -- which is one compile error per fuzz
    // test. With tracing off nothing in the runner asks for a trace, and the
    // fuzzers build and run. What it costs is the return trace under a
    // failing test; the error and the test's name are still printed.
    // The delta search runs its candidates on the caller's executor when
    // `PackOptions.threads` asks for more than one, and the suite writes
    // the same repository from two processes and two tasks at once. Whether
    // that is free of races is a claim a race detector can check and a
    // reader cannot: `zig build test -Dthread-sanitizer`.
    const thread_sanitizer = b.option(
        bool,
        "thread-sanitizer",
        "Build the tests with ThreadSanitizer",
    ) orelse false;

    const test_module = b.createModule(.{
        .root_source_file = b.path("src/tests.zig"),
        .target = target,
        .optimize = optimize,
        .sanitize_thread = if (thread_sanitizer) true else null,
        .error_tracing = false,
    });
    test_module.addImport("conduit", conduit);
    test_module.addOptions("relic_test_cases", case_options);
    filter_helper.root_module.addImport("relic", module);
    lfs_transfer_helper.root_module.addImport("relic", module);
    hook_fixture.root_module.addImport("relic", module);
    upload_pack_helper.root_module.addImport("relic", module);
    upload_pack_helper.root_module.addImport("conduit", conduit);
    hook_fixture.root_module.addImport("conduit", conduit);
    test_module.addOptions("build_options", build_options);

    const tests = b.addTest(.{
        .name = "relic-tests",
        .root_module = test_module,
        .filters = if (b.option([]const u8, "test-filter", "Select tests by name")) |filter| &.{filter} else case_names,
    });

    const run_tests = b.addRunArtifact(tests);
    if (b.graph.environ_map.get("RUNNER_TEMP")) |temp| {
        const old_git = std.mem.eql(u8, b.graph.environ_map.get("RELIC_GIT") orelse "", "old");
        const master_git = std.mem.eql(u8, b.graph.environ_map.get("RELIC_GIT") orelse "", "master");
        if (!old_git) {
            const root = b.pathJoin(&.{ temp, "preflight-tools" });
            const separator = if (b.graph.host.result.os.tag == .windows) ";" else ":";
            // Git's bin launcher starts another process. Use the native
            // executable and its Unix tools on the hosted Windows runner.
            const git_root = b.graph.environ_map.get("ProgramFiles") orelse "C:\\Program Files";
            const git_bin = if (b.graph.host.result.os.tag == .windows)
                b.pathJoin(&.{ git_root, "Git", "mingw64", "bin" })
            else
                b.pathJoin(&.{ root, if (master_git) "master" else "git", "bin" });
            const lfs_bin = b.pathJoin(&.{ root, "lfs", "bin" });
            const original_path = b.graph.environ_map.get("PATH") orelse "";
            const remaining_path = if (b.graph.host.result.os.tag == .windows)
                b.fmt("{s};{s}", .{ b.pathJoin(&.{ git_root, "Git", "usr", "bin" }), original_path })
            else
                original_path;
            run_tests.setEnvironmentVariable("PATH", b.fmt("{s}{s}{s}{s}{s}", .{ git_bin, separator, lfs_bin, separator, remaining_path }));
        }
        if (b.graph.host.result.os.tag == .linux and !old_git) run_tests.setEnvironmentVariable("RELIC_REQUIRE_SIGNERS", "1");
    }
    run_tests.step.dependOn(&install_lock_helper.step);
    run_tests.step.dependOn(&install_filter_helper.step);
    run_tests.step.dependOn(&install_lfs_transfer_helper.step);
    run_tests.step.dependOn(&install_upload_pack_helper.step);
    run_tests.step.dependOn(&install_hook_fixture.step);
    run_tests.step.dependOn(&install_fake_ssh.step);
    run_tests.step.dependOn(&install_lfs_tool.step);
    run_tests.step.dependOn(&install_process_fixture.step);
    run_tests.step.dependOn(&install_remote_helper.step);

    const test_step = b.step("test", "Run the relic tests");
    test_step.dependOn(&run_tests.step);

    // Compiling without running: the step a cross-compilation check uses,
    // and the one an editor can keep warm. It covers the tests too, which
    // the default install step does not.
    const check_step = b.step("check", "Compile everything without running it");
    check_step.dependOn(&tests.step);
    check_step.dependOn(&lock_helper.step);
    check_step.dependOn(&filter_helper.step);
    check_step.dependOn(&lfs_transfer_helper.step);
    check_step.dependOn(&upload_pack_helper.step);
    check_step.dependOn(&hook_fixture.step);
    check_step.dependOn(&fake_ssh.step);
    check_step.dependOn(&lfs_tool.step);
    check_step.dependOn(&process_fixture.step);
    check_step.dependOn(&remote_helper.step);

    //=====================================================================
    // Examples
    //
    // Built AND run, against the module a consumer gets. An example that is
    // only compiled proves the names still resolve; running it is what
    // proves the bytes are still the bytes. examples/usage.zig is also where
    // README.md's Usage block comes from -- see zig build docs -- usage -- so the
    // snippet a reader copies cannot drift from code CI executes.
    //=====================================================================

    const examples_step = b.step("examples", "Build and run the examples");
    for (example_sources) |source| {
        const example = b.addExecutable(.{
            .name = std.fs.path.stem(source),
            .root_module = b.createModule(.{
                .root_source_file = b.path(source),
                .target = target,
                .optimize = optimize,
                .imports = &.{.{ .name = "relic", .module = module }},
            }),
        });
        b.installArtifact(example);
        check_step.dependOn(&example.step);
        const run = b.addRunArtifact(example);
        run.step.dependOn(b.getInstallStep());
        run.setCwd(b.path("zig-out"));
        examples_step.dependOn(&run.step);

        const example_tests = b.addTest(.{ .root_module = example.root_module });
        const run_example_tests = b.addRunArtifact(example_tests);
        examples_step.dependOn(&run_example_tests.step);
        check_step.dependOn(&example_tests.step);
    }
    test_step.dependOn(examples_step);
    preflight.addCi(b, .{ .tests = test_step });
    namespaceImportChecker(b);
    _ = ciCheck(b, "check-cases", "ci/cases_check.zig");
    _ = ciCheck(b, "check-git-flags", "ci/git_checks.zig");
    const setup = b.addExecutable(.{ .name = "ci-setup", .root_module = b.createModule(.{ .root_source_file = b.path("ci/setup.zig"), .target = b.graph.host, .optimize = .ReleaseSafe }) });
    const prepare = b.addRunArtifact(setup);
    if (b.args) |args| prepare.addArgs(args);
    b.step("ci-setup", "Install cached Git and LFS tools").dependOn(&prepare.step);
    // Keep the package root at src so the moved check can embed its TLS sibling.
    const tls_test = b.addTest(.{ .root_module = test_module, .filters = &.{"the TLS client is std's, with the recorded diff and nothing else"} });
    b.step("check-tls-fork", "Verify the TLS fork against std and its recorded patch").dependOn(&b.addRunArtifact(tls_test).step);
    const tls_writer = b.addExecutable(.{ .name = "tls-fork", .root_module = b.createModule(.{ .root_source_file = b.path("ci/tls_fork.zig"), .target = b.graph.host, .optimize = .ReleaseSafe }) });
    const tls_writer_options = b.addOptions();
    tls_writer_options.addOption([]const u8, "std_tls_client", b.graph.zig_lib_directory.join(b.allocator, &.{ "std", "crypto", "tls", "Client.zig" }) catch @panic("OOM"));
    tls_writer.root_module.addOptions("build_options", tls_writer_options);
    b.step("tls-fork", "Re-record the TLS client's patch against std").dependOn(&b.addRunArtifact(tls_writer).step);
}

/// Every example, listed rather than globbed: a build graph that scans a
/// directory is not reproducible from the manifest alone.
const example_sources = [_][]const u8{
    "examples/usage.zig",
};

// Build-only tooling belongs to a root invocation, never a consumer's dependency graph.
fn ciCheck(b: *std.Build, name: []const u8, source: []const u8) *std.Build.Step.Compile {
    const module = b.createModule(.{ .root_source_file = b.path(source), .target = b.graph.host, .optimize = .Debug });
    const executable = b.addExecutable(.{ .name = name, .root_module = module });
    const tests = b.addTest(.{ .root_module = module });
    const run = b.addRunArtifact(executable);
    run.setCwd(b.path("."));
    const step = b.step(name, "Run repository CI checks and their regressions");
    step.dependOn(&b.addRunArtifact(tests).step);
    step.dependOn(&run.step);
    return executable;
}

// Main keeps namespace reexports outside implementation layer and cycle checks.
// Both shared structure invocations use this same compile step, so retain
// main's checker while the pinned preflight provides the rest of the gate.
fn namespaceImportChecker(b: *std.Build) void {
    if (b.pkg_hash.len != 0) return;
    const structure = b.top_level_steps.get("check-imports") orelse return;
    const runner = structure.step.dependencies.items[0].cast(std.Build.Step.Run) orelse @panic("expected import-check run");
    const checker = runner.producer orelse @panic("expected import-check compiler");
    checker.root_module.root_source_file = b.path("ci/imports.zig");
}
