const std = @import("std");
const testing = std.testing;
const Allocator = std.mem.Allocator;
const Io = std.Io;
const Identity = @import("../wire/url.zig").Identity;
const ParseError = @import("../wire/url.zig").ParseError;
const Scheme = @import("../wire/url.zig").Scheme;
const Url = @import("../wire/url.zig").Url;
const anonymize = @import("../wire/url.zig").anonymize;
const isLocal = @import("../wire/url.zig").isLocal;
const testgit = @import("git.zig");
const hash = @import("../hash/hash.zig");
const local = @import("../transport/local.zig");
const Oid = hash.Oid;
const Kind = hash.Kind;
test "encoded file URL paths reach the same repository as Git" {
    const gpa = testing.allocator;
    const io = testing.io;
    var fixture = try testgit.Repo.init(gpa, io, &.{});
    defer fixture.deinit();
    try fixture.exec(io, &.{ "init", "-q", "--bare", "a b%20" });
    const path = try fixture.dir.realPathFileAlloc(io, "a b%20", gpa);
    defer gpa.free(path);
    const escaped_percent = try std.mem.replaceOwned(u8, gpa, path, "%", "%25");
    defer gpa.free(escaped_percent);
    const escaped = try std.mem.replaceOwned(u8, gpa, escaped_percent, " ", "%20");
    defer gpa.free(escaped);
    const text = try gpa.print("file://{s}", .{escaped});
    defer gpa.free(text);
    try fixture.exec(io, &.{ "ls-remote", text });
    var remote = try local.Remote.open(gpa, io, text, .{});
    defer remote.deinit(io);
    try testing.expect(remote.repo.isBare());
}
