//! Source layers, lowest first. Every source has one explicit place.
const gantry = @import("gantry");

pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "primitives", .patterns = &.{
        "src/crc32.zig",

        "src/cquote.zig",
        "src/odb/delta.zig",
        "src/dependencies.zig",
        "src/repo/fs/durability.zig",
        "src/ere.zig",
        "src/ewah.zig",
        "src/object/gitdate.zig",
        "src/worktree/encoding.zig",
        "src/transport/httpauth.zig",
        "src/odb/inflate.zig",
        "src/testing/lfs/tool.zig",
        "src/testing/lock.zig",
        "src/patch/mail/format.zig",
        "src/patch/mail.zig",
        "src/lfs/mimesniff.zig",
        "src/lfs/netrc.zig",
        "src/pathspec.zig",
        "src/repo/fs/stat.zig",
        "src/testing/process.zig",
        "src/transport/progress.zig",
        "src/repo/diagnostic.zig",
        "src/worktree/safepath.zig",
        "src/transport/socks.zig",
        "src/hash/sha1.zig",
        "src/hash/sha1dc.zig",
        "src/testing/case.zig",
        "src/testing/io.zig",
        "src/testing/git.zig",
        "src/testing/program.zig",
        "src/diff/textdiff.zig",
        "src/lfs/timetext.zig",
        "src/transport/tls/der.zig",
        "src/transport/tls/rsa.zig",
        "src/testing/tls_fork.zig",
        "src/unicodewidth.zig",
        "src/varint.zig",
        "src/repo/warning.zig",

        "src/patch/whitespace.zig",
        "src/worktree/wildmatch.zig",
    } },
    .{ .name = "binary and process inputs", .patterns = &.{
        "src/patch/binary.zig",
        "src/merge/blobmerge.zig",
        "src/testing/fake_ssh.zig",
        "src/repo/fs.zig",
        "src/hash.zig",
        "src/transport/pktline.zig",
        "src/repo/program.zig",
        "src/diff/similarity.zig",
        "src/transport/tls/key.zig",
        "src/transport/url.zig",
    } },
    .{ .name = "formats and file policy", .patterns = &.{
        "src/odb/accelerators/chunks.zig",
        "src/odb/commitgraph/bloom.zig",
        "src/odb/bitmap.zig",
        "src/worktree/attributes.zig",
        "src/transport/auth.zig",
        "src/odb/commitgraph.zig",
        "src/config/write.zig",
        "src/transport/connection.zig",
        "src/worktree/dirscan.zig",
        "src/testing/filter.zig",
        "src/testing/hook.zig",
        "src/worktree/ignore.zig",
        "src/testing/lfs/transfer.zig",
        "src/odb/midx.zig",
        "src/object.zig",
        "src/patch.zig",
        "src/transport/refspec.zig",
        "src/refs/reftable.zig",
        "src/revwalk/shallow.zig",
        "src/transport/sideband.zig",
        "src/merge/strategy.zig",
        "src/testing/remote.zig",
        "src/transport/tls/ClientAuth.zig",
        "src/commit/todo.zig",
    } },
    .{ .name = "object and config values", .patterns = &.{
        "src/config.zig",
        "src/transport/filterspec.zig",
        "src/object/fsck.zig",
        "src/odb/inflate_test.zig",
        "src/lfs/ssh.zig",
        "src/commit/message.zig",
        "src/odb/pack/entry.zig",
        "src/transport/protocol.zig",
        "src/refs/reflog.zig",
        "src/worktree/sparse.zig",
        "src/testing/lfs.zig",
        "src/transport/tls/auth_wire.zig",
    } },
    .{ .name = "repository policy", .patterns = &.{
        "src/diff/userdiff.zig",
        "src/config/state.zig",
        "src/transport/credential.zig",
        "src/submodule/gitmodules.zig",
        "src/repo/hooks.zig",
        "src/transport/httpsettings.zig",
        "src/lfs.zig",
        "src/transport/remote.zig",
        "src/odb/revindex.zig",
        "src/commit/signing.zig",
        "src/transport/ssh.zig",
        "src/refs/reftablestack/policy.zig",
        "src/transport/tls/Client.zig",
        "src/config/userconfig.zig",
    } },
    .{ .name = "storage formats", .patterns = &.{
        "src/worktree/filter.zig",
        "src/odb/pack.zig",
        "src/refs/value.zig",
        "src/refs/packed.zig",
        "src/refs/reftablestack/cache.zig",
        "src/transport/tls.zig",
    } },
    .{ .name = "storage contracts", .patterns = &.{
        "src/odb/bitmap/reachability.zig",
        "src/transport/clientcert.zig",
        "src/transport/httpclient.zig",
        "src/odb/policy.zig",
        "src/refs/state.zig",
    } },
    .{ .name = "storage machinery", .patterns = &.{
        "src/odb/state.zig",
        "src/refs/reftablestack/transaction.zig",
        "src/transport/smarthttp.zig",
    } },
    .{ .name = "store construction", .patterns = &.{
        "src/odb/open.zig",
        "src/refs.zig",
    } },
    .{ .name = "store owners", .patterns = &.{
        "src/odb.zig",
        "src/refs/reftablestack.zig",
    } },
    .{ .name = "object operations", .patterns = &.{
        "src/odb/abbrev.zig",
        "src/submodule/gitlink.zig",
        "src/commit/cache.zig",
        "src/index.zig",
        "src/diff/rename.zig",
        "src/revwalk.zig",
        "src/revwalk/simplify.zig",
        "src/transport/sendpack.zig",
        "src/merge/subtreeshift.zig",
        "src/transport/objectwalk/filter.zig",
        "src/worktree/worktrees.zig",
    } },
    .{ .name = "object transforms", .patterns = &.{
        "src/testing/concurrency.zig",
        "src/worktree/convert.zig",
        "src/diff.zig",
        "src/transport/objectfilter.zig",
        "src/pretty.zig",
        "src/revwalk_test.zig",
        "src/index/sparseindex.zig",
    } },
    .{ .name = "worktree and merge policy", .patterns = &.{
        "src/diff_test.zig",
        "src/merge/ort.zig",
        "src/diff/blame.zig",
        "src/diff/patchid.zig",
        "src/worktree.zig",
    } },
    .{ .name = "repositories", .patterns = &.{
        "src/merge.zig",
        "src/merge/ort_test.zig",
        "src/repo.zig",
        "src/merge/strategy_test.zig",
    } },
    .{ .name = "repository operations", .patterns = &.{
        "src/diff/blame_test.zig",
        "src/revwalk/bisect.zig",

        "src/archive.zig",
        "src/archive_test.zig",
        "src/clean.zig",
        "src/clean_test.zig",
        "src/commit/commithooks.zig",
        "src/testing/config_refresh.zig",
        "src/revwalk/describe.zig",
        "src/testing/embedded_repo.zig",
        "src/worktree/filter_test.zig",
        "src/testing/fixtures.zig",
        "src/patch/format.zig",
        "src/grep.zig",
        "src/grep_test.zig",
        "src/commit/head.zig",
        "src/odb/indexpack.zig",
        "src/lfs/api.zig",
        "src/commit/notes.zig",
        "src/testing/packwrite.zig",
        "src/testing/refs_ownership.zig",
        "src/refs/reftablestack_test.zig",
        "src/repo_test.zig",
        "src/odb/revindex_test.zig",
        "src/revwalk/mailmap.zig",
        "src/revwalk/revparse.zig",
        "src/revwalk/shortlog.zig",
        "src/worktree/snapshot.zig",
        "src/worktree/sparsecheckout.zig",
        "src/index/sparseindex_test.zig",
        "src/commit/stash.zig",
        "src/submodule.zig",
        "src/merge/threeway.zig",
        "src/testing/workcount.zig",
        "src/worktree_test.zig",
    } },
    .{ .name = "object transfer", .patterns = &.{
        "src/testing/eol.zig",
        "src/testing/encoding.zig",
        "src/lfs_test.zig",
        "src/lfs/locks.zig",
        "src/transport/objectwalk.zig",
        "src/odb/accelerators.zig",
        "src/odb/accelerators_test.zig",
        "src/merge/rerere.zig",
        "src/commit/reset.zig",
        "src/worktree/snapshot_test.zig",
        "src/commit/stash_test.zig",
        "src/submodule_test.zig",
    } },
    .{ .name = "commit and local transport", .patterns = &.{
        "src/transport/bundle.zig",

        "src/patch/apply.zig",
        "src/patch/apply_test.zig",
        "src/patch/format_test.zig",
        "src/commit.zig",
        "src/transport/fetchpack.zig",
        "src/lfs/hooks.zig",
        "src/lfs/transfer.zig",
        "src/transport/local.zig",
        "src/commit/merging.zig",
    } },
    .{ .name = "transfer orchestration", .patterns = &.{
        "src/patch/am.zig",
        "src/patch/am_test.zig",
        "src/transport/clone/lfs.zig",
        "src/lfs/push.zig",
        "src/lfs/transfer_test.zig",
        "src/commit/sequencer.zig",
        "src/transport/uploadpack.zig",
        "src/testing/url_ownership.zig",
    } },
    .{ .name = "remote sessions", .patterns = &.{
        "src/lfs/locks_test.zig",
        "src/lfs/ssh_test.zig",
        "src/commit/rebase.zig",
        "src/transport.zig",
        "src/testing/uploadpack.zig",
    } },
    .{ .name = "history and remote operations", .patterns = &.{
        "src/testing/history.zig",
        "src/transport/partial.zig",
        "src/transport/push.zig",
        "src/commit/signing_test.zig",
    } },
    .{ .name = "fetch and clone", .patterns = &.{
        "src/transport/clone.zig",
        "src/transport/fetch.zig",
        "src/lfs/push_test.zig",
    } },
    .{ .name = "transport scenarios", .patterns = &.{
        "src/transport/auth_test.zig",
        "src/transport/bundle_test.zig",
        "src/transport/clientcert_test.zig",
        "src/testing/cloneconfig.zig",
        "src/transport/partial_test.zig",
        "src/revwalk/shallow_test.zig",
        "src/submodule/transport.zig",
        "src/transport_test.zig",
        "src/transport/uploadpack_test.zig",
    } },
    .{ .name = "submodules", .patterns = &.{} },
    .{ .name = "public", .patterns = &.{
        "src/relic.zig",
        "src/tests.zig",
    } },
};

pub const entries: []const []const u8 = &.{
    "src/testing/fake_ssh.zig",
    "src/testing/filter.zig",
    "src/testing/hook.zig",
    "src/testing/lfs/tool.zig",
    "src/testing/lfs/transfer.zig",
    "src/testing/lock.zig",
    "src/testing/process.zig",
    "src/testing/uploadpack.zig",
};

pub const modules: []const gantry.NamedModule = &.{
    .{ .name = "root", .path = "src/tests.zig", .from = "src/testing/concurrency.zig" },
    .{ .name = "relic", .path = "src/relic.zig", .from = "src/testing/**" },
};
pub const references: []const gantry.rules.ReferenceRule = &.{
    .{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{
        "build_options",
        "builtin",
        "conduit",
        "relic_test_cases",
        "root",
        "std",
    } },
    .{ .name = "source siblings", .suffix = ".zig", .relative = true, .except_targets = &.{"src/**"} },
    .{ .name = "conduit owner", .target = "conduit", .except_from = &.{"src/dependencies.zig"} },
    .{ .name = "relic_test_cases owner", .target = "relic_test_cases", .except_from = &.{"src/testing/case.zig"} },
};

pub const required = blk: {
    var count: usize = 0;
    for (layers) |layer| count += layer.patterns.len;
    var paths: [count][]const u8 = undefined;
    var i: usize = 0;
    for (layers) |layer| for (layer.patterns) |path| {
        paths[i] = path;
        i += 1;
    };
    break :blk paths;
};

/// Tokens only their owners may spell: starting and waiting on processes is
/// conduit's, and this package's Windows declarations live in one file.
pub const owned: []const gantry.rules.TokenRule = &.{
    .{ .name = "process owner", .token = "waitpid" },
    .{ .name = "process owner", .token = "wait4" },
    .{ .name = "process owner", .token = "execve" },
    .{ .name = "process owner", .token = "posix_spawn" },
    .{ .name = "process owner", .token = "setsid" },
    .{ .name = "process owner", .token = "CreateProcessW" },
    // the ssh stand-in is another program, holding its handles as ssh does
    .{ .name = "windows declarations", .kind = .string, .token = "kernel32", .owners = &.{ "src/repo/fs.zig", "src/testing/fake_ssh.zig" } },
};

/// Namespace reexports added when each facade was folded into its implementation.
/// Implementation imports still obey the original layers and cycle checks.
pub const namespace_exports: []const gantry.Edge = &.{
    .{ .from = "src/repo.zig", .to = "src/repo/warning.zig", .kind = .import },
    .{ .from = "src/object.zig", .to = "src/object/fsck.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/indexpack.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/revindex.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/commitgraph.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/bitmap.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/accelerators.zig", .kind = .import },
    .{ .from = "src/odb.zig", .to = "src/odb/abbrev.zig", .kind = .import },
    .{ .from = "src/refs.zig", .to = "src/refs/reftablestack.zig", .kind = .import },
    .{ .from = "src/config.zig", .to = "src/config/userconfig.zig", .kind = .import },
    .{ .from = "src/index.zig", .to = "src/index/sparseindex.zig", .kind = .import },
    .{ .from = "src/worktree.zig", .to = "src/worktree/snapshot.zig", .kind = .import },
    .{ .from = "src/worktree.zig", .to = "src/worktree/worktrees.zig", .kind = .import },
    .{ .from = "src/worktree.zig", .to = "src/worktree/sparsecheckout.zig", .kind = .import },
    .{ .from = "src/worktree.zig", .to = "src/worktree/wildmatch.zig", .kind = .import },
    .{ .from = "src/diff.zig", .to = "src/diff/patchid.zig", .kind = .import },
    .{ .from = "src/diff.zig", .to = "src/diff/blame.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/transport/objectwalk.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/revparse.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/mailmap.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/shortlog.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/describe.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/bisect.zig", .kind = .import },
    .{ .from = "src/revwalk.zig", .to = "src/revwalk/simplify.zig", .kind = .import },
    .{ .from = "src/merge.zig", .to = "src/merge/strategy.zig", .kind = .import },
    .{ .from = "src/merge.zig", .to = "src/merge/subtreeshift.zig", .kind = .import },
    .{ .from = "src/merge.zig", .to = "src/merge/threeway.zig", .kind = .import },
    .{ .from = "src/merge.zig", .to = "src/merge/rerere.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/stash.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/merging.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/sequencer.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/rebase.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/todo.zig", .kind = .import },
    .{ .from = "src/commit.zig", .to = "src/commit/notes.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/remote.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/refspec.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/fetch.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/clone.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/push.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/httpclient.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/tls.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/clientcert.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/httpauth.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/httpsettings.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/sideband.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/objectwalk.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/objectfilter.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/partial.zig", .kind = .import },
    .{ .from = "src/transport.zig", .to = "src/transport/filterspec.zig", .kind = .import },
    .{ .from = "src/submodule.zig", .to = "src/submodule/transport.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/api.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/transfer.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/locks.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/push.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/hooks.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/ssh.zig", .kind = .import },
    .{ .from = "src/lfs.zig", .to = "src/lfs/netrc.zig", .kind = .import },
    .{ .from = "src/patch.zig", .to = "src/patch/apply.zig", .kind = .import },
    .{ .from = "src/patch.zig", .to = "src/patch/format.zig", .kind = .import },
    .{ .from = "src/patch.zig", .to = "src/patch/mail.zig", .kind = .import },
    .{ .from = "src/patch.zig", .to = "src/patch/am.zig", .kind = .import },
    .{ .from = "src/testing/filter.zig", .to = "src/relic.zig", .kind = .import },
    .{ .from = "src/testing/hook.zig", .to = "src/relic.zig", .kind = .import },
    .{ .from = "src/testing/lfs/transfer.zig", .to = "src/relic.zig", .kind = .import },
    .{ .from = "src/testing/uploadpack.zig", .to = "src/relic.zig", .kind = .import },
};
