//! Source layers, lowest first. Every source has one explicit place.
const gantry = @import("gantry");

pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "primitives", .patterns = &.{
        "src/cquote.zig",
        "src/delta.zig",
        "src/dependencies.zig",
        "src/durability.zig",
        "src/ere.zig",
        "src/ewah.zig",
        "src/gitdate.zig",
        "src/httpauth.zig",
        "src/inflate.zig",
        "src/lfs_test_tool.zig",
        "src/lock_helper.zig",
        "src/mailfmt.zig",
        "src/mailinfo.zig",
        "src/mimesniff.zig",
        "src/netrc.zig",
        "src/pathspec.zig",
        "src/platstat.zig",
        "src/process_fixture.zig",
        "src/progress.zig",
        "src/repodiagnostic.zig",
        "src/safepath.zig",
        "src/sha1.zig",
        "src/sha1dc.zig",
        "src/test_case.zig",
        "src/testgit.zig",
        "src/testprogram.zig",
        "src/textdiff.zig",
        "src/timetext.zig",
        "src/tls/der.zig",
        "src/tls/rsa.zig",
        "src/tls_fork_test.zig",
        "src/unicodewidth.zig",
        "src/varint.zig",
        "src/warning.zig",
        "src/whitespace.zig",
        "src/wildmatch.zig",
    } },
    .{ .name = "binary and process inputs", .patterns = &.{
        "src/binarypatch.zig",
        "src/blobmerge.zig",
        "src/fake_ssh_helper.zig",
        "src/fs.zig",
        "src/hash.zig",
        "src/pktline.zig",
        "src/program.zig",
        "src/similarity.zig",
        "src/tls/key.zig",
        "src/url.zig",
    } },
    .{ .name = "formats and file policy", .patterns = &.{
        "src/attributes.zig",
        "src/auth.zig",
        "src/commitgraph.zig",
        "src/config_write.zig",
        "src/connection.zig",
        "src/dirscan.zig",
        "src/filter_helper.zig",
        "src/hook_fixture.zig",
        "src/ignore.zig",
        "src/lfs_transfer_helper.zig",
        "src/midx.zig",
        "src/object_core.zig",
        "src/patchparse.zig",
        "src/refspec.zig",
        "src/reftable.zig",
        "src/shallow.zig",
        "src/sideband.zig",
        "src/strategy.zig",
        "src/testremote.zig",
        "src/tls/ClientAuth.zig",
        "src/todo.zig",
    } },
    .{ .name = "object and config values", .patterns = &.{
        "src/config_core.zig",
        "src/filterspec.zig",
        "src/fsck.zig",
        "src/inflate_test.zig",
        "src/lfsssh.zig",
        "src/message.zig",
        "src/pack_types.zig",
        "src/protocol.zig",
        "src/reflog.zig",
        "src/sparse.zig",
        "src/testlfs.zig",
        "src/tls/auth_wire.zig",
    } },
    .{ .name = "repository policy", .patterns = &.{
        "src/configstate.zig",
        "src/credential.zig",
        "src/gitmodules.zig",
        "src/hooks.zig",
        "src/httpsettings.zig",
        "src/lfs_core.zig",
        "src/object.zig",
        "src/remote.zig",
        "src/revindex.zig",
        "src/signing.zig",
        "src/ssh.zig",
        "src/stack_types.zig",
        "src/tls/Client.zig",
        "src/userconfig.zig",
    } },
    .{ .name = "storage formats", .patterns = &.{
        "src/config.zig",
        "src/filter.zig",
        "src/pack.zig",
        "src/ref_types.zig",
        "src/stack_cache.zig",
        "src/tls/root.zig",
    } },
    .{ .name = "storage contracts", .patterns = &.{
        "src/clientcert.zig",
        "src/httpclient.zig",
        "src/odb_types.zig",
        "src/refstate.zig",
    } },
    .{ .name = "storage machinery", .patterns = &.{
        "src/odbstate.zig",
        "src/reftable_ops.zig",
        "src/smarthttp.zig",
    } },
    .{ .name = "store construction", .patterns = &.{
        "src/odbinit.zig",
        "src/refs_core.zig",
    } },
    .{ .name = "store owners", .patterns = &.{
        "src/odb_core.zig",
        "src/reftablestack.zig",
    } },
    .{ .name = "object operations", .patterns = &.{
        "src/abbrev.zig",
        "src/gitlink.zig",
        "src/index_core.zig",
        "src/refs.zig",
        "src/rename.zig",
        "src/revwalk_core.zig",
        "src/sendpack.zig",
        "src/subtreeshift.zig",
        "src/walk_types.zig",
        "src/worktrees.zig",
    } },
    .{ .name = "object transforms", .patterns = &.{
        "src/concurrency_test.zig",
        "src/convert.zig",
        "src/diff_core.zig",
        "src/objectfilter.zig",
        "src/pretty.zig",
        "src/revwalk_test.zig",
        "src/sparseindex.zig",
    } },
    .{ .name = "worktree and merge policy", .patterns = &.{
        "src/diff_test.zig",
        "src/index.zig",
        "src/ort.zig",
        "src/patchid.zig",
        "src/worktree_core.zig",
    } },
    .{ .name = "repositories", .patterns = &.{
        "src/diff.zig",
        "src/merge_core.zig",
        "src/ort_test.zig",
        "src/repo_core.zig",
        "src/strategy_test.zig",
    } },
    .{ .name = "repository operations", .patterns = &.{
        "src/archive.zig",
        "src/archive_test.zig",
        "src/clean.zig",
        "src/clean_test.zig",
        "src/commithooks.zig",
        "src/config_refresh_test.zig",
        "src/embedded_repo_test.zig",
        "src/filter_test.zig",
        "src/fixture_test.zig",
        "src/formatpatch.zig",
        "src/grep.zig",
        "src/grep_test.zig",
        "src/head.zig",
        "src/indexpack.zig",
        "src/lfsapi.zig",
        "src/packwrite_test.zig",
        "src/refs_owner_test.zig",
        "src/reftablestack_test.zig",
        "src/repo.zig",
        "src/repo_test.zig",
        "src/revindex_test.zig",
        "src/revparse.zig",
        "src/snapshot.zig",
        "src/sparsecheckout.zig",
        "src/sparseindex_test.zig",
        "src/stash.zig",
        "src/submodule_core.zig",
        "src/threeway.zig",
        "src/workcount_test.zig",
        "src/worktree_test.zig",
    } },
    .{ .name = "object transfer", .patterns = &.{
        "src/eol_test.zig",
        "src/lfs_test.zig",
        "src/lfslocks.zig",
        "src/objectwalk.zig",
        "src/odb.zig",
        "src/rerere.zig",
        "src/reset.zig",
        "src/revwalk.zig",
        "src/snapshot_test.zig",
        "src/stash_test.zig",
        "src/submodule_test.zig",
        "src/worktree.zig",
    } },
    .{ .name = "commit and local transport", .patterns = &.{
        "src/apply.zig",
        "src/apply_test.zig",
        "src/formatpatch_test.zig",
        "src/commit_core.zig",
        "src/fetchpack.zig",
        "src/lfshooks.zig",
        "src/lfstransfer.zig",
        "src/local.zig",
        "src/merge.zig",
        "src/merging.zig",
    } },
    .{ .name = "transfer orchestration", .patterns = &.{
        "src/am_core.zig",
        "src/am_test.zig",
        "src/clonelfs.zig",
        "src/lfspush.zig",
        "src/lfstransfer_test.zig",
        "src/sequencer.zig",
        "src/uploadpack.zig",
        "src/url_owner_test.zig",
    } },
    .{ .name = "remote sessions", .patterns = &.{
        "src/lfs.zig",
        "src/lfslocks_test.zig",
        "src/lfsssh_test.zig",
        "src/rebase.zig",
        "src/transport_core.zig",
        "src/uploadpack_helper.zig",
    } },
    .{ .name = "history and remote operations", .patterns = &.{
        "src/commit.zig",
        "src/patch.zig",
        "src/history_test.zig",
        "src/partial.zig",
        "src/push.zig",
        "src/signing_test.zig",
    } },
    .{ .name = "fetch and clone", .patterns = &.{
        "src/clone.zig",
        "src/fetch.zig",
        "src/lfspush_test.zig",
    } },
    .{ .name = "transport scenarios", .patterns = &.{
        "src/auth_test.zig",
        "src/clientcert_test.zig",
        "src/cloneconfig_test.zig",
        "src/partial_test.zig",
        "src/shallow_test.zig",
        "src/submoduletransport.zig",
        "src/transport.zig",
        "src/transport_test.zig",
        "src/uploadpack_test.zig",
    } },
    .{ .name = "submodules", .patterns = &.{
        "src/submodule.zig",
    } },
    .{ .name = "public", .patterns = &.{
        "src/relic.zig",
    } },
};

pub const entries: []const []const u8 = &.{
    "src/fake_ssh_helper.zig",
    "src/filter_helper.zig",
    "src/hook_fixture.zig",
    "src/lfs_test_tool.zig",
    "src/lfs_transfer_helper.zig",
    "src/lock_helper.zig",
    "src/process_fixture.zig",
    "src/uploadpack_helper.zig",
};

pub const modules: []const gantry.NamedModule = &.{.{ .name = "root", .path = "src/relic.zig", .from = "src/concurrency_test.zig" }};
pub const references: []const gantry.rules.ReferenceRule = &.{
    .{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{
        "build_options",
        "builtin",
        "conduit",
        "relic_test_cases",
        "root",
        "std",
    } },
    .{ .name = "source siblings", .suffix = ".zig", .relative = true, .except_targets = &.{"src/**"} },
    .{ .name = "conduit owner", .target = "conduit", .except_from = &.{"src/dependencies.zig"} },
    .{ .name = "relic_test_cases owner", .target = "relic_test_cases", .except_from = &.{"src/test_case.zig"} },
};

pub const required = blk: {
    var count: usize = 0;
    for (layers) |layer| count += layer.patterns.len;
    var paths: [count][]const u8 = undefined;
    var i: usize = 0;
    for (layers) |layer| for (layer.patterns) |path| {
        paths[i] = path;
        i += 1;
    };
    break :blk paths;
};

/// Tokens only their owners may spell: starting and waiting on processes is
/// conduit's, and this package's Windows declarations live in one file.
pub const owned: []const gantry.rules.TokenRule = &.{
    .{ .name = "process owner", .token = "waitpid" },
    .{ .name = "process owner", .token = "wait4" },
    .{ .name = "process owner", .token = "execve" },
    .{ .name = "process owner", .token = "posix_spawn" },
    .{ .name = "process owner", .token = "setsid" },
    .{ .name = "process owner", .token = "CreateProcessW" },
    // the ssh stand-in is another program, holding its handles as ssh does
    .{ .name = "windows declarations", .kind = .string, .token = "kernel32", .owners = &.{ "src/fs.zig", "src/fake_ssh_helper.zig" } },
};
