const std = @import("std");
const testing = std.testing;
const Allocator = std.mem.Allocator;
const Io = std.Io;
const Identity = @import("url.zig").Identity;
const ParseError = @import("url.zig").ParseError;
const Scheme = @import("url.zig").Scheme;
const Url = @import("url.zig").Url;
const anonymize = @import("url.zig").anonymize;
const isLocal = @import("url.zig").isLocal;
const testgit = @import("testgit.zig");
const hash = @import("hash.zig");
const Oid = hash.Oid;
const Kind = hash.Kind;
test "encoded file URL paths reach the same repository as Git" {
    const gpa = testing.allocator;
    const io = testing.io;
    var fixture = try @import("testgit.zig").Repo.init(gpa, io, &.{});
    defer fixture.deinit();
    try fixture.exec(io, &.{ "init", "-q", "--bare", "a b%20" });
    const path = try fixture.dir.realPathFileAlloc(io, "a b%20", gpa);
    defer gpa.free(path);
    const escaped_percent = try std.mem.replaceOwned(u8, gpa, path, "%", "%25");
    defer gpa.free(escaped_percent);
    const escaped = try std.mem.replaceOwned(u8, gpa, escaped_percent, " ", "%20");
    defer gpa.free(escaped);
    const text = try std.fmt.allocPrint(gpa, "file://{s}", .{escaped});
    defer gpa.free(text);
    try fixture.exec(io, &.{ "ls-remote", text });
    var remote = try @import("local.zig").Remote.open(gpa, io, text);
    defer remote.deinit(io);
    try testing.expect(remote.repo.isBare());
}
